"""CPU-only precision-control manifest validation; no framework/model calls."""
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
root=Path('outputs/preference_program/manifests');source=root/'framing_factorial_v42.jsonl'
base=[json.loads(x) for x in source.read_text().splitlines() if json.loads(x)['header']=='numbers' and json.loads(x)['instruction']=='label'];assert len(base)==4
rows=[]
for precision in ('NF4','BF16'):
 for b in base:
  rows.append({'precision':precision,'permutation_id':b['permutation_id'],'case_id':b['case_id'],'prompt':b['prompt'],'prompt_sha256':b['prompt_sha256'],'displayed_values':b['displayed_values'],'gold_action':b['gold_action'],'messages':[{'role':'user','content':b['prompt']}]})
for k in range(4):
 pair=[r for r in rows if r['permutation_id']==k];assert len(pair)==2
 assert {r['precision'] for r in pair}=={'NF4','BF16'}
 assert {r['prompt_sha256'] for r in pair}=={hashlib.sha256(pair[0]['prompt'].encode()).hexdigest()}
 assert pair[0]['messages']==pair[1]['messages'] and pair[0]['gold_action']==pair[1]['gold_action']
 assert pair[0]['gold_action']=='ABCD'[pair[0]['displayed_values'].index(max(pair[0]['displayed_values']))]
m=root/'precision_control_v43.jsonl';m.write_text(''.join(json.dumps(r)+'\n' for r in rows))
scoring={'parser_regex':r'\s*([ABCD])\s*','correctness':'strict fullmatch equals displayedintegerargmax;parsefailure countedincorrect andseparately','paired_primary':'BF16minusNF4 correctness perrotation;report4differences andmean;noCI','diagnostics':['changedlabeloutputs','correcttoincorrect andincorrecttocorrect counts','parsefailures','EOS/lengthcaps','botharmcellcorrect/4','memory/load/generationtimings'],'decision_criterion':'BF16=4/4withzeroparse/truncation andNF4<4/4 supports precision-sensitive failure for this frozenassay;doesnotqualify generalcapability;freshcase gate required. Both<4/4: assaygate fails,seekguidance. Both4/4: no detectedprecisionloss here,earlierprompt/runtime differences remain;freshcasequalification required. NF4passes/BF16fails: precisiontradeoff,do notadopt BF16. Incomplete/resourcesfail: no scientificcomparison;no retry.','meaning':'one reusedcase/fourrotations: criterion onlylocalmeasurementgate,notpopulationevidence'}
s=root/'precision_control_v43_scoring.json';s.write_text(json.dumps(scoring,indent=2)+'\n')
protocol={'status':'frozenpreparationonly;noGPU/modelcalls/submission','created_at_utc':datetime.now(timezone.utc).isoformat(),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'records':8,'model':'Qwen/Qwen2.5-1.5B-Instruct','snapshot':'989aa7980e4cf806f80c7fef2b1adb7bc71aa306','weights_sha256':'dd924a11b4c220f385b51ffa522daea7c9f3d850e31b162bb5661df483c6d3ee','shared_loader_contract':{'pretrained_model_name_or_path':'verifiedexplicit_snapshot','local_files_only':True,'trust_remote_code':True,'torch_dtype':'torch.bfloat16','device_map':{'':'cuda:0'},'attention_implementation':'sameinstalledframeworkdefaultrecordeffectivevaluebotharms','use_cache':False,'eval':True},'precision_difference':{'NF4':{'load_in_4bit':True,'bnb_4bit_quant_type':'nf4','bnb_4bit_compute_dtype':'torch.bfloat16','bnb_4bit_use_double_quant':True},'BF16':{'quantization_config':None}},'tokenizer_contract':'samepinnedsnapshot/nativeapply_chat_template(add_generation_prompt=True),identical singleuser messages,noexplicit extra systemmessage;assertprompttokenIDs identical acrossarms','decode':{'do_sample':False,'max_new_tokens':24,'pad_token_id':'same tokenizer EOS','eos':'sameeffectivegenerationconfigEOSIDs'},'arm_order':'NF4thenBF16,loadsequentially,neverretainbothmodels;deleteNF4references/collect/emptyCUDAcacheandrecordmemorybeforeBF16;orderconfoundedwithprecision,time/allocatornuisance notisolated','token_custody':['promptIDs/renderedmessages','generatedIDs','promptlength','effectiveEOSIDs','generatedlength','lasttoken','EOSobserved','lengthcap','snapshot/runtimehashes','effectiveparameterdtypes/quantizationsettings'], 'resources_if_authorized':{'gpu':'oneH200MIG2g.35gb','walltime':'00:05:00','cpu_memory':'32G','staging_watchdog_seconds':45,'load_watchdog_seconds_per_arm':90,'memory_planning_budget_GiB':12,'generation_watchdog_seconds_per_arm':10,'noautomatic_retry':True},'memory_assessment':'BF16weightpayload2.875GiB;planningbudget12GiB includes two-copyallowance plusCUDA/workspace/activation headroom,NOTmeasuredpeak orproof ofruntimefit;recordprocessmemory andstoponbudget breach;35GBMIG provides additionalheadroom','time_assessment':'staging45+twoloads180+twogeneration10+orchestration/finalization allowance40=285seconds;watchdogs bound attempt,not completionguarantee. BF16loading/inferenceunmeasured;do notclaimfive-minute completion','criterion':scoring['decision_criterion'],'limitations':'onlyprecision-package outputcomparisonononefixedassay;quantizedkernel/codepath changes intrinsic;armorder notcounterbalanced;no preference recovery orbroaderinference','gate':'Review memory/time feasibility beforeauthorization;no blindrun/320study/tuning','hashes':{'manifest':hashlib.sha256(m.read_bytes()).hexdigest(),'scoring':hashlib.sha256(s.read_bytes()).hexdigest(),'preparation_script':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}}
p=root/'precision_control_v43_protocol.json';p.write_text(json.dumps(protocol,indent=2)+'\n')
(root/'precision_control_v43_validation.json').write_text(json.dumps({'CPU_only':True,'model_calls':0,'GPUallocations':0,'records':8,'prompt_and_messages_equal_acrossprecision':True,'gold_equal_and_balanced':True,'precision_onlyarmfielddifference':True,'manifest_sha256':hashlib.sha256(m.read_bytes()).hexdigest(),'protocol_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'scoring_sha256':hashlib.sha256(s.read_bytes()).hexdigest()},indent=2)+'\n')
print('Frozen8prompt precisionpairs;CPUchecked identities;no model calls orGPUallocation')
